### ISSUE TITLE
Cannot run multiple .cfg using the same check commands

### ISSUE THREAD

**Issue by jgamos** [PVasileff/main-nagios-plugins#1]
Hi OP

tried using the same .cfg for another devices and i wont allow me to restart nagios, but when disabling the other .cfg it runs normally.

**Comment by PVasileff** [comment]
Can you provide me an example about that you talk?

**Comment by jgamos** [comment]
example i have router1.cfg 
##
define host {
        use                     generic-switch
        host_name         Router1
        alias                   router1
        address                 192.168.0.1
}

# 'check_mikrotik_uptime' command definition
define command {
        command_name check_mikrotik_uptime
        command_line $USER1$/check_mikrotik_uptime -H $HOSTADDRESS$ $ARG1$
}

define service {
        use                             generic-service
        host_name                       xxxx
        service_description             UPTIME
        check_interval                  1
        max_check_attempts              5
        contact_groups                  xxxx
        check_command                   check_mikrotik_uptime!-P 3 -C $USER3$ -L authPriv -U $USER3$ -a SHA -A $USER4$ -x AES -X $USER5$
}


and also i have router2.cfg
define host {
        use                     generic-switch
        host_name         Router2
        alias                   router2
        address                 192.168.0.2
}

# 'check_mikrotik_uptime' command definition
define command {
        command_name check_mikrotik_uptime
        command_line $USER1$/check_mikrotik_uptime -H $HOSTADDRESS$ $ARG1$
}

define service {
        use                             generic-service
        host_name                       xxxx
        service_description             UPTIME
        check_interval                  1
        max_check_attempts              5
        contact_groups                  xxxx
        check_command                   check_mikrotik_uptime!-P 3 -C $USER3$ -L authPriv -U $USER3$ -a SHA -A $USER4$ -x AES -X $USER5$
}


- my issue was when both router1.cfg and router2.cfg will run i get error when restarting the nagios service.
- but when i disable router2.cfg  (add # in nagios.cfg) i can restart nagios service and it works okay.

i think the problem is i cannot use the same check_mikrotik_uptime file in libexec directory?

i wanted to add multiple router with similar check_command using the mikrotik script you made.

thanks for the reply OP
